version: "3.8"

services:
  prolog:
    build:
      context: .
      dockerfile: Dockerfile.prolog
    ports:
      - "3030:3030"
    volumes:
      - ./swipl-home:/root/.swipl-dir

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - prolog
